AllCops:
  NewCops: disable
  TargetRubyVersion: 2.6

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 120
  Severity: convention

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
