AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 120
  Severity: convention

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
